
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  
  screen: { flex: 1, backgroundColor: "#ffffffff" },
  container: { flex: 1, flexDirection: "row" },
  sidebarWrapper: {
    width: 256,
    backgroundColor: "#FFFFFF",
    borderRightWidth: 1,
    borderRightColor: "#E5E7EB",
  },
  sidebarMobile: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: 256,
    backgroundColor: "#FFFFFF",
    zIndex: 40,
    elevation: 40,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 30,
    elevation: 30,
  },
  mainContent: { flex: 1 },
  header: {
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    paddingHorizontal: 24,
    paddingTop: 48, 
    paddingBottom: 16, 
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTextSecondary: { fontSize: 14, color: "#4B5563" },
  headerTextPrimary: { fontSize: 14, fontWeight: "500" },
  button: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 6,
  },
  buttonText: { color: "#374151" },
  menuButton: {
    position: "absolute",
    top: 52, 
    left: 16,
    zIndex: 50,
    elevation: 50,
    backgroundColor: "#FFFFFF",
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  sidebarContainer: { flex: 1, paddingTop: 24, paddingHorizontal: 12 }, 
  sidebarTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    paddingHorizontal: 12,
  },
  sidebarItemWrapper: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  sidebarItemWrapperActive: { backgroundColor: "#F3F4F6" },
  sidebarItem: { fontSize: 16, marginLeft: 12, color: "#4b5563" },
  sidebarItemActive: { fontWeight: "600", color: "#2563eb" }, 
  formContainer: {
    flex: 1, 
    padding: 24,
    backgroundColor: "#FFFFFF",
    margin: 20,
    borderRadius: 12,
    elevation: 2,

    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
  },
  formHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  formTitle: { 
    fontSize: 20, 
    fontWeight: "bold", 
    color: "#1F2937",
    flex: 1, 
    marginRight: 10, 
  }, 
  formSubtitle: { fontSize: 14, color: "#6B7280", marginBottom: 24 }, 
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 14, color: "#374151", marginBottom: 8, fontWeight: "500" }, 
  input: {
    borderWidth: 1,
    borderColor: "#D1D5DB", 
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: "#F9FAFB", 
    color: "#1F2937", 
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#D1D5DB", 
    borderRadius: 8,
    backgroundColor: "#F9FAFB", 
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  picker: {
    height: 50,
    flex: 1,
    backgroundColor: 'transparent', 
    borderWidth: 0, 
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#1F2937', 
    appearance: 'none', 
    WebkitAppearance: 'none', 
  },
  pickerIconContainer: { 
    position: 'absolute',
    right: 0,
    height: '100%',
    justifyContent: 'center',
    paddingHorizontal: 12,
    pointerEvents: 'none', 
  },
  registerButton: {
    backgroundColor: "#2563eb", 
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 8,
  },
  registerButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "bold" },
  backButton: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  backButtonText: {
    color: "#2563eb", 
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 4,
  },
  listContainer: {
    flex: 1,
    padding: 20,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  addUserButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2563eb", 
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexShrink: 0, 
  },
  addUserButtonText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    marginLeft: 8,
    fontSize: 14,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 12,
    marginBottom: 16, 
  },
  searchInputIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1F2937',
  },
  filterBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 16, 
  },
  filterGroup: {
    flex: 1, 
  },
  filterPicker: {
    height: 50,
  },
  userItem: { 
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB", 
    marginBottom: 12,
    overflow: 'hidden', 
  },
  userItemHeader: { 
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  userItemText: { 
    flex: 1, 
    marginRight: 10, 
  },
  userName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1F2937", 
  },
  userEmail: {
    fontSize: 12,
    color: "#6B7280", 
    marginTop: 2,
  },
  userItemRoleContainer: { 
     alignItems: 'flex-end', 
  },
  userItemRole: { 
    fontWeight: "500",
    overflow: 'hidden', 
    paddingVertical: 4, 
    paddingHorizontal: 8, 
    borderRadius: 4, 
    marginBottom: 5, 
    textAlign: 'center', 
    minWidth: 90, 
    fontSize: 14,
  },
  roleAdmin: { color: "#D97706", backgroundColor: "#FEF3C7" }, 
  roleEmpleado: { color: "#059669", backgroundColor: "#D1FAE5" }, 
  roleBodeguero: { color: "#1D4ED8", backgroundColor: "#DBEAFE" }, 
  roleSocio: { color: "#7E22CE", backgroundColor: "#F3E8FF" }, 
  roleMaquinaria: { color: "#4B5563", backgroundColor: "#F3F4F6" }, 
  roleProveedor: { color: "#0891B2", backgroundColor: "#CFFAFE" }, 
  
  
  roleSupervisor: { color: "#FFFFFF", backgroundColor: "#1F2937" }, 

  
  
  statusEnEspera: { color: "#D97706", backgroundColor: "#FEF3C7" },   
  statusEnProceso: { color: "#1D4ED8", backgroundColor: "#DBEAFE" }, 
  statusRechazada: { color: "#DC2626", backgroundColor: "#FEE2E2" }, 
  statusRecibido: { color: "#059669", backgroundColor: "#D1FAE5" },  
  
  statusPendiente: { color: "#D97706", backgroundColor: "#FEF3C7" }, 
  statusCancelado: { color: "#DC2626", backgroundColor: "#FEE2E2" }, 
  

  ellipsisButton: { 
    padding: 5, 
  },
  emptyListText: { 
    textAlign: "center",
    marginTop: 40,
    fontSize: 14,
    color: "#6B7280", 
  },
  expandedDetailsContainer: { 
    paddingHorizontal: 16, 
    paddingBottom: 16, 
    borderTopWidth: 1, 
    borderTopColor: '#E5E7EB', 
    marginTop: 10, 
  },
  detailRow: { 
    flexDirection: 'row',
    marginBottom: 8, 
    alignItems: 'center', 
  },
  detailLabel: { 
    fontSize: 12,
    fontWeight: '600', 
    color: '#4B5563', 
    width: 90, 
    marginRight: 8, 
  },
  detailValue: { 
    fontSize: 12,
    color: '#110000ff', 
    flex: 1, 
  },
  expandedActionsContainer: { 
      flexDirection: 'row',
      justifyContent: 'flex-end', 
      flexWrap: 'wrap', 
      marginTop: 12, 
      paddingTop: 12, 
      borderTopWidth: 1, 
      borderTopColor: '#E5E7EB', 
  },
  actionButton: { 
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginLeft: 10, 
    marginTop: 8, 
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1, 
  },
  editButton: { 
    backgroundColor: '#DBEAFE', 
    borderColor: '#93C5FD', 
  },
  deleteButton: { 
    backgroundColor: '#FEE2E2', 
    borderColor: '#FCA5A5', 
  },
  actionButtonText: { 
    fontSize: 13, 
    fontWeight: '450',
    marginLeft: 6, 
  },
  editButtonText: { color: '#1D4ED8' }, 
  deleteButtonText: { color: '#B91C1C' }, 
  pedidoButton: {
    backgroundColor: '#2563eb', 
    borderColor: '#1D4ED8', 
  },
  pedidoButtonText: {
    color: '#FFFFFF', 
  },
  statusButton: {
    backgroundColor: '#D1FAE5', 
    borderColor: '#6EE7B7', 
  },
  statusButtonText: {
    color: '#047857', 
  },
  cancelButton: {
    backgroundColor: '#FEE2E2', 
    borderColor: '#FCA5A5', 
  },
  cancelButtonText: {
    color: '#B91C1C', 
  },

  dateInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#fbf9f9ff',
  },
  dateInputText: {
    fontSize: 16,
    color: '#1F2937',
    flex: 1,
  },
  dateInputTextPlaceholder: {
    fontSize: 16,
    color: '#9CA3AF', 
    flex: 1,
  },
  dateInputIcon: {
    marginLeft: 8,
  },
  
  
  tabBar: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 4,
  },
  tabIndicator: { 
    height: 3, 
    backgroundColor: '#2563eb', 
    borderRadius: 3 
  },
  tabLabel: { 
    fontWeight: "600", 
    color: '#6B7280', 
    textTransform: 'none', 
    fontSize: 14,
  },
  
});